// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"api/internal/handler/admin/activity"
	"api/internal/handler/admin/goods"
	"api/internal/handler/admin/home"
	"api/internal/handler/admin/points"
	"api/internal/handler/admin/scenic"
	"api/internal/handler/admin/user"
	"net/http"

	"api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/xiaohe",
				Handler: ApiHandler(serverCtx),
			},
		},
	)
	//登入和退出操作
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "login",
				Handler: user.AdminLoginHandler(serverCtx), //管理员登入
			},
		},
		rest.WithPrefix("/admin/manager/"),
	)
	//超级管理员对管理员的操作
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserMiddle},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "UpdateInfo",
					Handler: user.UpdateInfoHandler(serverCtx), //管理员修改自己个人信息
				},
				{
					Method:  http.MethodPost,
					Path:    "getAdminUserList",
					Handler: user.GetAdminUserListHandler(serverCtx), //获取管理员列表
				},
				{
					Method:  http.MethodPost,
					Path:    "addAdminUser",
					Handler: user.AddAdminUserHandler(serverCtx), //添加管理员
				},
				{
					Method:  http.MethodPost,
					Path:    "updateAdminUser",
					Handler: user.UpdateAdminUserHandler(serverCtx), //修改管理员密码或状态
				},
			}...,
		),
		rest.WithPrefix("/admin/manager/"),
	)
	//管理员对签到活动的管理操作
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserMiddle},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "list",
					Handler: activity.SigninActivityListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "add",
					Handler: activity.SigninActivityAddHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "updateInfo",
					Handler: activity.SigninActivityUpdateInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "delete",
					Handler: activity.SigninActivityDeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin/activity/signin/"),
	)
	//管理员对秒杀活动的管理操作
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserMiddle},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "list",
					Handler: activity.SeckillActivityListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "add",
					Handler: activity.SeckillActivityAddHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "updateInfo",
					Handler: activity.SeckillActivityUpdateInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "delete",
					Handler: activity.SeckillActivityDeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin/activity/seckill/"),
	)
	//管理员对秒杀活动商品的管理
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserMiddle},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "list",
					Handler: activity.SeckillGoodListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "add",
					Handler: activity.SeckillGoodAddHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "updateInfo",
					Handler: activity.SeckillGoodUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "delete",
					Handler: activity.SeckillGoodDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "batchUpdatePrice",
					Handler: activity.SeckillGoodBatchUpdatePriceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "batchDelete",
					Handler: activity.SeckillGoodBatchDeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin/activity/seckill/good/"),
	)
	//管理员对签到活动-景点关联的管理
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserMiddle},
			[]rest.Route{
				{Method: http.MethodPost, Path: "list",       Handler: activity.SigninScenicListHandler(serverCtx)},
				{Method: http.MethodPost, Path: "add",        Handler: activity.SigninScenicAddHandler(serverCtx)},
				{Method: http.MethodPost, Path: "updateInfo", Handler: activity.SigninScenicUpdateHandler(serverCtx)},
				{Method: http.MethodPost, Path: "delete",     Handler: activity.SigninScenicDeleteHandler(serverCtx)},
			}...,
		),
		rest.WithPrefix("/admin/activity/signin/scenic/"),
	)
	//管理员对商品的管理
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserMiddle},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "add",
					Handler: goods.GoodAddHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "list",
					Handler: goods.GoodListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "update",
					Handler: goods.GoodUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "delete",
					Handler: goods.GoodDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "updateStatus",
					Handler: goods.GoodUpdateStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin/good/"),
	)
	//管理员对活动配置的管理
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserMiddle},
			[]rest.Route{
				{Method: http.MethodPost, Path: "list",         Handler: home.ActivityConfigListHandler(serverCtx)},
				{Method: http.MethodPost, Path: "add",          Handler: home.ActivityConfigAddHandler(serverCtx)},
				{Method: http.MethodPost, Path: "updateInfo",   Handler: home.ActivityConfigUpdateHandler(serverCtx)},
				{Method: http.MethodPost, Path: "delete",       Handler: home.ActivityConfigDeleteHandler(serverCtx)},
				{Method: http.MethodPost, Path: "setDefault",   Handler: home.ActivityConfigSetDefaultHandler(serverCtx)},
				{Method: http.MethodPost, Path: "updateStatus", Handler: home.ActivityConfigUpdateStatusHandler(serverCtx)},
			}...,
		),
		rest.WithPrefix("/admin/home/activityConfig/"),
	)
	//管理员对活动配置项的管理
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserMiddle},
			[]rest.Route{
				{Method: http.MethodPost, Path: "list",       Handler: home.ActivityConfigItemListHandler(serverCtx)},
				{Method: http.MethodPost, Path: "add",        Handler: home.ActivityConfigItemAddHandler(serverCtx)},
				{Method: http.MethodPost, Path: "updateInfo", Handler: home.ActivityConfigItemUpdateHandler(serverCtx)},
				{Method: http.MethodPost, Path: "delete",     Handler: home.ActivityConfigItemDeleteHandler(serverCtx)},
			}...,
		),
		rest.WithPrefix("/admin/home/activityConfig/item/"),
	)
	//管理员对公告的管理
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserMiddle},
			[]rest.Route{
				{Method: http.MethodPost, Path: "list",         Handler: home.NoticeListHandler(serverCtx)},
				{Method: http.MethodPost, Path: "add",          Handler: home.NoticeAddHandler(serverCtx)},
				{Method: http.MethodPost, Path: "updateInfo",   Handler: home.NoticeUpdateHandler(serverCtx)},
				{Method: http.MethodPost, Path: "delete",       Handler: home.NoticeDeleteHandler(serverCtx)},
				{Method: http.MethodPost, Path: "updateStatus", Handler: home.NoticeStatusHandler(serverCtx)},
			}...,
		),
		rest.WithPrefix("/admin/notice/"),
	)
	//管理员对兑换规则的管理
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserMiddle},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "list",
					Handler: points.PointsRoleListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "add",
					Handler: points.PointsRoleAddHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "update",
					Handler: points.PointsRoleUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin/pointsRole/"),
	)
	//管理员对景点的管理
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserMiddle},
			[]rest.Route{
				{Method: http.MethodPost, Path: "list",         Handler: scenic.ScenicSpotListHandler(serverCtx)},
				{Method: http.MethodPost, Path: "add",          Handler: scenic.ScenicSpotAddHandler(serverCtx)},
				{Method: http.MethodPost, Path: "updateInfo",   Handler: scenic.ScenicSpotUpdateHandler(serverCtx)},
				{Method: http.MethodPost, Path: "delete",       Handler: scenic.ScenicSpotDeleteHandler(serverCtx)},
				{Method: http.MethodPost, Path: "updateStatus", Handler: scenic.ScenicSpotUpdateStatusHandler(serverCtx)},
			}...,
		),
		rest.WithPrefix("/admin/scenic/"),
	)
	//用户相关操作
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserMiddle},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "list",
					Handler: user.GetUserListHander(serverCtx), //用户列表
				},
				{
					Method:  http.MethodPost,
					Path:    "updatePwd",
					Handler: user.UpdatePwdUserHander(serverCtx), //重置用户密码
				},
				{
					Method:  http.MethodPost,
					Path:    "updateUserPoints",
					Handler: user.UpdateUserPointsHander(serverCtx), //修改用户积分
				},
				{
					Method:  http.MethodPost,
					Path:    "pointsList",
					Handler: user.UserPointsListHander(serverCtx), //用户积分记录
				},
				{
					Method:  http.MethodPost,
					Path:    "add",
					Handler: user.AddUserHander(serverCtx), //新增用户
				},
				{
					Method:  http.MethodPost,
					Path:    "updateInfo",
					Handler: user.UpdateUserInfoHander(serverCtx), //修改用户基本信息
				},
			}...,
		),
		rest.WithPrefix("/admin/user/"),
	)
}
